/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbd_lcd.gui.form.peminjam;
import dbd_lcd.gui.MyPanel;
import dbd_lcd.PopupRunnable;
import dbd_lcd.RequireLoginRunnable;
import dbd_lcd.Util;
import dbd_lcd.gui.form.DialogKonfirmasi;
import dbd_lcd.gui.form.FormLogin;
import dbd_lcd.gui.form.peminjam.DetailPeminjamFrame.Mode;
import dbd_lcd.system.structs.Peminjam;

/**
 *
 * @author user
 */
public class DetailPeminjamPanel extends MyPanel {
    public int mode;
    Peminjam peminjam;
    /**
     * Creates new form DetailPeminjamanPanel
     */
    public DetailPeminjamPanel() {
        initComponents();
    }

    public void setMode(int mode){
        switch(mode){
            case Mode.TAMBAH:{
                blacklistSP.setVisible(false);
                blacklistLabel.setVisible(false);
                
                setReadOnly(false);
                
                closeButton.setVisible(true);
                addButton.setVisible(true);
                
                editButton.setVisible(false);
                saveButton.setVisible(false);
                doneButton.setVisible(false);
                cancelEditButton.setVisible(false);
                break;
            }
            case Mode.EDIT:{
                setReadOnly(false);
                idPeminjamField.setEditable(false);
                
                cancelEditButton.setVisible(true);
                saveButton.setVisible(true);
                
                closeButton.setVisible(false);
                addButton.setVisible(false);
                doneButton.setVisible(false);
                editButton.setVisible(false);
                
                getFrame().lockTab(this);
                
                break;
            }
            case Mode.LIHAT:{
                setReadOnly(true);
                
                editButton.setVisible(true);
                doneButton.setVisible(true);
                
                closeButton.setVisible(false);
                addButton.setVisible(false);
                saveButton.setVisible(false);
                cancelEditButton.setVisible(false);
                
                getFrame().lockTab(null);
                break;
            }
        }
    }
    public Peminjam read(){
        String id = getIdPeminjam();
        String nama = Util.nullify(namaPeminjamField.getText().trim());
        String noHp = Util.nullify(Util.preparePhoneNumber(nomorHpField.getText()));
        String alamat = Util.nullify(alamatTA.getText().trim());
        String ket = Util.nullify(blacklistTA.getText());
        if(id == null || id.length() < 9) throw new RuntimeException("Nomor Identitas tidak valid");
        if(nama == null || nama.length() < 3) throw new RuntimeException("Nama tidak valid");
        if(noHp == null || noHp.length() < 10) throw new RuntimeException("Nomor HP tidak valid");
        if (alamat == null || alamat.length() < 5) throw new RuntimeException("Alamat tidak valid");
        Peminjam pm = new Peminjam(id, nama, alamat, noHp, ket);
        return pm;
    }
    
    public void setReadOnly(boolean readOnly){
        idPeminjamField.setEditable(!readOnly);
        namaPeminjamField.setEditable(!readOnly);
        nomorHpField.setEditable(!readOnly);
        alamatTA.setEditable(!readOnly);
        blacklistTA.setEditable(!readOnly);
    }
    
    public void setIdPeminjam(String nomorIdentitas){
        this.idPeminjamField.setText(nomorIdentitas);
    }

    
    public String getIdPeminjam(){
        return Util.nullify(Util.preparePhoneNumber(idPeminjamField.getText()));
    }
    
    public void load(Peminjam pm){
        this.peminjam = pm;
        setIdPeminjam(pm.getIdPeminjam());
        namaPeminjamField.setText(pm.getNamaPeminjam());
        nomorHpField.setText(pm.getNomorHpPeminjam());
        alamatTA.setText(pm.getAlamatPeminjam());
        if(pm.isPeminjamTerblacklist()){
            blacklistTA.setText(pm.getKeteranganBlacklist());
            blacklistSP.setVisible(true);
            blacklistLabel.setVisible(true);
        }else{
            blacklistTA.setText("");
            blacklistSP.setVisible(false);
            blacklistLabel.setVisible(false);
        }
        setMode(Mode.LIHAT);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idPeminjamField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        namaPeminjamField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nomorHpField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatTA = new javax.swing.JTextArea();
        blacklistLabel = new javax.swing.JLabel();
        blacklistSP = new javax.swing.JScrollPane();
        blacklistTA = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        cancelEditButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        doneButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new java.awt.GridBagLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("No. Identitas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        jPanel3.add(jLabel1, gridBagConstraints);

        idPeminjamField.setEditable(false);
        idPeminjamField.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        idPeminjamField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        idPeminjamField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPeminjamFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        jPanel3.add(idPeminjamField, gridBagConstraints);
        new dbd_lcd.gui.LimitDocumentFilter(18).attach(idPeminjamField);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        jPanel3.add(jLabel3, gridBagConstraints);

        namaPeminjamField.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        namaPeminjamField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPeminjamFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        jPanel3.add(namaPeminjamField, gridBagConstraints);
        new dbd_lcd.gui.LimitDocumentFilter(64).attach(namaPeminjamField);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No. HP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        jPanel3.add(jLabel4, gridBagConstraints);

        nomorHpField.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        nomorHpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomorHpFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        jPanel3.add(nomorHpField, gridBagConstraints);
        new dbd_lcd.gui.LimitDocumentFilter(14).attach(nomorHpField);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Alamat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 20, 10, 10);
        jPanel3.add(jLabel2, gridBagConstraints);

        alamatTA.setColumns(20);
        alamatTA.setRows(5);
        jScrollPane1.setViewportView(alamatTA);
        new dbd_lcd.gui.LimitDocumentFilter(256).attach(alamatTA);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        jPanel3.add(jScrollPane1, gridBagConstraints);

        blacklistLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        blacklistLabel.setForeground(new java.awt.Color(255, 0, 0));
        blacklistLabel.setText("Terblacklist");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 20, 10, 10);
        jPanel3.add(blacklistLabel, gridBagConstraints);

        blacklistTA.setColumns(20);
        blacklistTA.setRows(5);
        blacklistSP.setViewportView(blacklistTA);
        new dbd_lcd.gui.LimitDocumentFilter(256).attach(blacklistTA);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        jPanel3.add(blacklistSP, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel3, gridBagConstraints);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbd_lcd/gui/image/SILANG.png"))); // NOI18N
        closeButton.setContentAreaFilled(false);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        jPanel4.add(closeButton);

        cancelEditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbd_lcd/gui/image/SILANG.png"))); // NOI18N
        cancelEditButton.setContentAreaFilled(false);
        cancelEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelEditButtonActionPerformed(evt);
            }
        });
        jPanel4.add(cancelEditButton);

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbd_lcd/gui/image/PENGATURAN.png"))); // NOI18N
        editButton.setContentAreaFilled(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jPanel4.add(editButton);

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbd_lcd/gui/image/CENTANG.png"))); // NOI18N
        addButton.setContentAreaFilled(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel4.add(addButton);

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbd_lcd/gui/image/CENTANG.png"))); // NOI18N
        saveButton.setContentAreaFilled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel4.add(saveButton);

        doneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbd_lcd/gui/image/CENTANG.png"))); // NOI18N
        doneButton.setContentAreaFilled(false);
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        jPanel4.add(doneButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 20);
        add(jPanel4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void idPeminjamFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPeminjamFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPeminjamFieldActionPerformed

    private void namaPeminjamFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPeminjamFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPeminjamFieldActionPerformed

    private void nomorHpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorHpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomorHpFieldActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        getFrame().dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void cancelEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEditButtonActionPerformed
        // TODO add your handling code here:
        load(peminjam);
    }//GEN-LAST:event_cancelEditButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        setMode(Mode.EDIT);
    }//GEN-LAST:event_editButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        final Peminjam pm;
        try{
            pm = read();
        }catch(Exception ex){
            Util.handleError(getFrame(), ex);
            return;
        }
        FormLogin.cekDanMintaSesi(getFrame(), new PopupRunnable(){
            @Override
            public boolean run(boolean success){
                if(success){
                    peminjam = pm;
                    try{
                        pm.insert();
                        getFrame().dispose(true);
                    }catch(Exception ex){
                        Util.handleException(getFrame(), ex);
                    }
                }
                return true;
            }
        });
    }//GEN-LAST:event_addButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        final Peminjam pm;
        try{
            pm = read();
        }catch(Exception ex){
            Util.handleException(getFrame(), ex);
            return;
        }
        if(pm.equals(peminjam)){
            setMode(Mode.LIHAT);
            return;
        }
        if(blacklistLabel.isVisible() && !pm.isPeminjamTerblacklist()){
            DialogKonfirmasi dk = new DialogKonfirmasi();
            dk.setQuestion(String.format("Apa anda yakin ingin menghilangkan status blacklist %s?", pm.getNamaPeminjam()));
            dk.setOnDispose(new RequireLoginRunnable(){
                @Override
                public void onLogin(){
                    peminjam = pm;
                    getFrame().changed = true;
                    peminjam.update();
                    load(peminjam);
                    setMode(Mode.LIHAT);
                    dk.dispose();
                }
            });
            setPopup(dk);
        }else{
            FormLogin.cekDanMintaSesi(getFrame(), new PopupRunnable(){
                public boolean run(boolean success){
                    if(success){
                        peminjam = pm;
                        getFrame().changed = true;
                        peminjam.update();
                        setMode(Mode.LIHAT);
                    }
                    return true;
                }
            });
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_doneButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextArea alamatTA;
    private javax.swing.JLabel blacklistLabel;
    private javax.swing.JScrollPane blacklistSP;
    private javax.swing.JTextArea blacklistTA;
    private javax.swing.JButton cancelEditButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton doneButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField idPeminjamField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namaPeminjamField;
    private javax.swing.JTextField nomorHpField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
