/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbd_lcd.gui.form.peminjam;

import dbd_lcd.PopupRunnable;
import dbd_lcd.RequireLoginRunnable;
import dbd_lcd.Util;
import dbd_lcd.gui.form.DialogKonfirmasi;
import dbd_lcd.gui.form.FormLogin;
import dbd_lcd.gui.form.peminjaman.DaftarPeminjamanPanel;
import dbd_lcd.system.LoginModule;
import dbd_lcd.system.structs.Peminjam;
import dbd_lcd.system.structs.filter.FilterPeminjam;
import dbd_lcd.system.structs.filter.FilterPeminjaman;

/**
 *
 * @author USER
 */
public class DetailPeminjamFrame extends dbd_lcd.gui.MyFrame {
    /**
     * Creates new form No_HP
     */
    
    public class Mode{
        public static final int TAMBAH = 0;
        public static final int EDIT = 1;
        public static final int LIHAT = 2;
    }
    public int mode;
    Peminjam peminjam;
    
    public DetailPeminjamFrame() {
        initComponents();
        setMode(Mode.TAMBAH);
    }
    
    public void setMode(int mode){
        this.mode = mode;
        switch(mode){
            case Mode.TAMBAH:{
                mainTabbedPane.remove(daftarPeminjamanPanel);
                break;
            }
            case Mode.EDIT:{
                mainTabbedPane.add(daftarPeminjamanPanel, "Peminjaman");
                mainTabbedPane.setEnabledAt(1, false);
                break;
            }
            case Mode.LIHAT:{
                mainTabbedPane.add(daftarPeminjamanPanel, "Peminjaman");
                mainTabbedPane.setEnabledAt(1, true);
                break;
            }
        }
        detailPeminjamPanel.setMode(mode);
    }
    
    public void load(Peminjam pm){
        this.peminjam = pm;
        detailPeminjamPanel.load(pm);
        
        FilterPeminjaman fp = daftarPeminjamanPanel.getFilter();
        FilterPeminjam filter = fp.peminjam;
        if(filter == null){
            filter = new FilterPeminjam();
        }
        filter.idPeminjam = peminjam.getIdPeminjam();
        fp.peminjam = filter;
        daftarPeminjamanPanel.setFilter(fp);
        setMode(Mode.LIHAT);
    }
    public String getIdPeminjam(){
        return detailPeminjamPanel.getIdPeminjam();
    }
    public void setIdPeminjam(String id){
        detailPeminjamPanel.setIdPeminjam(id);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        mainTabbedPane = new javax.swing.JTabbedPane();
        detailPeminjamPanel = new dbd_lcd.gui.form.peminjam.DetailPeminjamPanel();
        daftarPeminjamanPanel = new dbd_lcd.gui.form.peminjaman.DaftarPeminjamanPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(20, 375));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        mainTabbedPane.setBackground(new java.awt.Color(0, 102, 102));
        mainTabbedPane.setOpaque(true);
        mainTabbedPane.addTab("Detail", detailPeminjamPanel);
        mainTabbedPane.addTab("Peminjaman", daftarPeminjamanPanel);
        daftarPeminjamanPanel.setMode(DaftarPeminjamanPanel.Mode.SUB);

        getContentPane().add(mainTabbedPane, java.awt.BorderLayout.CENTER);
        setTabbedPane(mainTabbedPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailPeminjamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailPeminjamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailPeminjamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailPeminjamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailPeminjamFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dbd_lcd.gui.form.peminjaman.DaftarPeminjamanPanel daftarPeminjamanPanel;
    private dbd_lcd.gui.form.peminjam.DetailPeminjamPanel detailPeminjamPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane mainTabbedPane;
    // End of variables declaration//GEN-END:variables
}
