/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbd_lcd.gui.form.peminjaman;

import dbd_lcd.gui.MyPanel;
import dbd_lcd.gui.MyTableModel;
import dbd_lcd.PopupRunnable;
import dbd_lcd.Util;
import dbd_lcd.system.structs.KeperluanPinjam;
import dbd_lcd.system.structs.Peminjaman;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author user
 */
public class DaftarKeperluanPanel extends MyPanel {

    /**
     * Creates new form KeperluanPinjamPanel
     */
    List<KeperluanPinjam> keperluan = new ArrayList<KeperluanPinjam>(4);
    MyTableModel keperluanTableModel;
    boolean readOnly = false;
    public DaftarKeperluanPanel() {
        initComponents();
        prepareKeperluanTable();
    }
    
    public void setReadOnly(boolean readOnly){
        this.readOnly = readOnly;
        removeButton.setVisible(!readOnly);
        addButton.setVisible(!readOnly);
    }
    
    public void load(Peminjaman peminjaman){
        this.keperluan = new ArrayList<KeperluanPinjam>();
        int kl = peminjaman.getKeperluanPinjamCount();
        for(int i = 0; i < kl; ++i){
            KeperluanPinjam kp = peminjaman.getKeperluanPinjam(i);
            addKeperluan(kp);
        }
    }
    
    public KeperluanPinjam[] read(){
        return keperluan.toArray(new KeperluanPinjam[0]);
    }
    public void prepareKeperluanTable(){
        MyTableModel dtm = new MyTableModel();
        dtm.addColumn("Keperluan");
        dtm.addColumn("Jam Mulai");
        dtm.addColumn("Jam Selesai");
        keperluanTableModel = dtm;
        TabelKeperluanFP.setModel(dtm);
    }
    
    public void addKeperluan(KeperluanPinjam kp){
        keperluan.add(kp);
        keperluanTableModel.addRow(new String[]{
            kp.keperluanPinjam,
            Util.formatDateTime(kp.durasi.awal),
            Util.formatDateTime(kp.durasi.akhir)
        });
    }
    public void saveKeperluan(KeperluanPinjam kp, int index){
        keperluan.set(index, kp);
        keperluanTableModel.setValueAt(kp.keperluanPinjam, index, 0);
        keperluanTableModel.setValueAt(Util.formatTime(kp.durasi.awal), index, 1);
        keperluanTableModel.setValueAt(Util.formatTime(kp.durasi.akhir), index, 2);
    }
    public void removeKeperluan(int index){
        keperluanTableModel.removeRow(index);
        if(keperluan.remove(index) != null) throw new RuntimeException("Keperluan tidak ada");
        System.out.println("Jumlah keperluan: " + keperluan.size());
    }
    public void editKeperluan(){
        
        int row = TabelKeperluanFP.getSelectedRow();
        if(row < 0) return;
        editKeperluan(row);
    }
    public void editKeperluan(int row){
        KeperluanPinjam kp = keperluan.get(row);
        getFrame().setEnabled(false);
        DetailKeperluan tuk = new DetailKeperluan();
        tuk.setOnDispose(new PopupRunnable(){
            @Override
            public boolean run(boolean success){
                if(success) saveKeperluan(tuk.read(), row);
                return true;
            }
        });
        tuk.load(kp);
        tuk.setReadOnly(readOnly);
        setPopup(tuk);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane2 = new javax.swing.JScrollPane();
        TabelKeperluanFP = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        removeButton = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setBackground(new java.awt.Color(0, 102, 102));
        jScrollPane2.setOpaque(false);

        TabelKeperluanFP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Keperluan", "Jam Pinjam", "Jam Kembali"
            }
        ));
        TabelKeperluanFP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelKeperluanFPMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelKeperluanFP);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane2, gridBagConstraints);

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        removeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbd_lcd/gui/image/MIN.png"))); // NOI18N
        removeButton.setContentAreaFilled(false);
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        jPanel10.add(removeButton);

        viewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbd_lcd/gui/image/KC PMBESAR.png"))); // NOI18N
        viewButton.setContentAreaFilled(false);
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });
        jPanel10.add(viewButton);

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbd_lcd/gui/image/TAMBAH.png"))); // NOI18N
        addButton.setContentAreaFilled(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel10.add(addButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jPanel10, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void TabelKeperluanFPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelKeperluanFPMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() != 2) return;
        editKeperluan();
    }//GEN-LAST:event_TabelKeperluanFPMouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        setEnabled(false);
        DetailKeperluan tuk = new DetailKeperluan();
        tuk.setOnDispose(new PopupRunnable(){
            @Override
            public boolean run(boolean success){
                if(success) addKeperluan(tuk.read());
                return true;
            }
        });
        setPopup(tuk);
    }//GEN-LAST:event_addButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        editKeperluan();
    }//GEN-LAST:event_viewButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:

        int[] rows = TabelKeperluanFP.getSelectedRows();
        for(int i = rows.length-1; i >= 0; --i){
            removeKeperluan(rows[i]);
        }
    }//GEN-LAST:event_removeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelKeperluanFP;
    private javax.swing.JButton addButton;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
