/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbd_lcd.gui.form.peminjaman;

import dbd_lcd.PopupRunnable;
import dbd_lcd.gui.form.barang.*;
import dbd_lcd.gui.form.peminjam.*;
import dbd_lcd.Util;
import dbd_lcd.gui.form.peminjaman.*;
import dbd_lcd.system.structs.Barang;
import dbd_lcd.system.structs.Peminjaman;
import dbd_lcd.system.structs.RangeWaktu;
import dbd_lcd.system.structs.filter.FilterBarang;
import dbd_lcd.system.structs.filter.FilterKeperluanPinjam;
import dbd_lcd.system.structs.filter.FilterPeminjam;
import dbd_lcd.system.structs.filter.FilterPeminjaman;
import java.sql.Timestamp;

/**
 *
 * @author admin
 */
public class FilterPeminjamanFrame extends dbd_lcd.gui.MyFrame {

    /**
     * Creates new form Filter
     */
    FilterPeminjaman filter = new FilterPeminjaman();
    FilterBarang filterBarang = new FilterBarang();
    FilterPeminjam filterPeminjam = new FilterPeminjam();
    FilterKeperluanPinjam filterKeperluan = new FilterKeperluanPinjam();
    public FilterPeminjamanFrame() {
        initComponents();
    }

    public void load(FilterPeminjaman filter){
        statusCB.setSelectedItem(Util.stringify(Peminjaman.Status.TO_STRING.get(filter.status)));
        
        if(filter.rangeWaktu != null){
            waktuAwalField.setText(Util.stringify(Util.formatDateTime(filter.rangeWaktu.awal)));
            waktuAkhirField.setText(Util.stringify(Util.formatDateTime(filter.rangeWaktu.akhir)));
        }else{
            waktuAwalField.setText("");
            waktuAkhirField.setText("");
        }
        terlambatCB.setSelectedItem(Util.stringify(filter.terlambat));
        keteranganTA.setText(Util.stringify(filter.keterangan));
        
        this.filter = filter;
        this.filterBarang = new FilterBarang(filter.barang);
        this.filterPeminjam = new FilterPeminjam(filter.peminjam);
        this.filterKeperluan = new FilterKeperluanPinjam(filter.keperluan);
    }
    public FilterPeminjaman read(){
        FilterPeminjaman filter = new FilterPeminjaman(this.filter);
        filter.status = Peminjaman.Status.FROM_STRING.get(Util.nullify((String)statusCB.getSelectedItem())); 
        Timestamp waktuAwal = Util.parseDateTime(Util.nullify(waktuAwalField.getText()));
        Timestamp waktuAkhir = Util.parseDateTime(Util.nullify(waktuAkhirField.getText()));
        RangeWaktu rangeWaktu = null;
        if(waktuAwal != null || waktuAkhir != null){
            rangeWaktu = new RangeWaktu(waktuAwal, waktuAkhir);
            rangeWaktu.cekValid();
        }
        filter.rangeWaktu = rangeWaktu;
        filter.terlambat = Util.booleanify((String)terlambatCB.getSelectedItem());
        filter.keterangan = Util.nullify(keteranganTA.getText());
        
        filter.barang = new FilterBarang(filterBarang);
        filter.peminjam = new FilterPeminjam(filterPeminjam);
        filter.keperluan = new FilterKeperluanPinjam(filterKeperluan);
        
        return filter;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        statusCB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        peminjamButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        barangButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        keperluanButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        waktuAwalField = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        waktuAkhirField = new javax.swing.JFormattedTextField();
        tipeLabel = new javax.swing.JLabel();
        terlambatCB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        keteranganTA = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(15, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.WEST);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("Filter Peminjaman");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel4, gridBagConstraints);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Status");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jLabel3, gridBagConstraints);

        statusCB.setModel(new javax.swing.DefaultComboBoxModel<String>(Peminjaman.Status.FILTER_STRING));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(statusCB, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Peminjam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jLabel6, gridBagConstraints);

        peminjamButton.setBackground(new java.awt.Color(255, 153, 0));
        peminjamButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        peminjamButton.setText("Filter");
        peminjamButton.setOpaque(false);
        peminjamButton.setSelected(true);
        peminjamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjamButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(peminjamButton, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Barang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jLabel9, gridBagConstraints);

        barangButton.setBackground(new java.awt.Color(255, 153, 0));
        barangButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        barangButton.setText("Filter");
        barangButton.setOpaque(false);
        barangButton.setSelected(true);
        barangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(barangButton, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Keperluan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jLabel10, gridBagConstraints);

        keperluanButton.setBackground(new java.awt.Color(255, 153, 0));
        keperluanButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        keperluanButton.setText("Filter");
        keperluanButton.setOpaque(false);
        keperluanButton.setSelected(true);
        keperluanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keperluanButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(keperluanButton, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Waktu Awal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jLabel8, gridBagConstraints);

        waktuAwalField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm"))));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(waktuAwalField, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Waktu Akhir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jLabel7, gridBagConstraints);

        waktuAkhirField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm"))));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(waktuAkhirField, gridBagConstraints);

        tipeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tipeLabel.setForeground(new java.awt.Color(255, 255, 255));
        tipeLabel.setText("Terlambat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(tipeLabel, gridBagConstraints);

        terlambatCB.setModel(new javax.swing.DefaultComboBoxModel<String>(Util.getBooleanCBString()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(terlambatCB, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Keterangan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jLabel2, gridBagConstraints);

        keteranganTA.setColumns(20);
        keteranganTA.setRows(5);
        jScrollPane1.setViewportView(keteranganTA);
        new dbd_lcd.gui.LimitDocumentFilter(256).attach(keteranganTA);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel4.setOpaque(false);

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbd_lcd/gui/image/SILANG.png"))); // NOI18N
        cancelButton.setContentAreaFilled(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel4.add(cancelButton);

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbd_lcd/gui/image/CENTANG.png"))); // NOI18N
        saveButton.setContentAreaFilled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel4.add(saveButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        jPanel1.add(jPanel4, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        load(filter);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        try{
            load(read());
        }catch(RuntimeException ex){
            Util.handleError(this, ex);
        }
        changed = true;
        dispose(true);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void peminjamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjamButtonActionPerformed
        // TODO add your handling code here:
        FilterPeminjamFrame fpf = new FilterPeminjamFrame();
        fpf.load(filterPeminjam);
        fpf.setOnDispose(new PopupRunnable(){
            @Override
            public boolean run(boolean success){
                if(success){
                    filterPeminjam = fpf.read();
                }
                return true;
            }
        });
        setPopup(fpf);
    }//GEN-LAST:event_peminjamButtonActionPerformed

    private void barangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangButtonActionPerformed
        // TODO add your handling code here:
        FilterBarangFrame fpf = new FilterBarangFrame();
        fpf.setTipeCBVisible(true);
        fpf.load(filterBarang);
        fpf.setOnDispose(new PopupRunnable(){
            @Override
            public boolean run(boolean success){
                if(success){
                    filterBarang = fpf.read();
                }
                return true;
            }
        });
        setPopup(fpf);
    }//GEN-LAST:event_barangButtonActionPerformed

    private void keperluanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keperluanButtonActionPerformed
        // TODO add your handling code here:
        FilterKeperluanFrame fpf = new FilterKeperluanFrame();
        fpf.load(filterKeperluan);
        fpf.setOnDispose(new PopupRunnable(){
            @Override
            public boolean run(boolean success){
                if(success){
                    filterKeperluan = fpf.read();
                }
                return true;
            }
        });
        setPopup(fpf);
    }//GEN-LAST:event_keperluanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilterPeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilterPeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilterPeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilterPeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilterPeminjamanFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barangButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keperluanButton;
    private javax.swing.JTextArea keteranganTA;
    private javax.swing.JButton peminjamButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> statusCB;
    private javax.swing.JComboBox<String> terlambatCB;
    private javax.swing.JLabel tipeLabel;
    private javax.swing.JFormattedTextField waktuAkhirField;
    private javax.swing.JFormattedTextField waktuAwalField;
    // End of variables declaration//GEN-END:variables
}
