/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbd_lcd.gui.form.barang;
import dbd_lcd.gui.MyPanel;
import dbd_lcd.PopupRunnable;
import dbd_lcd.Util;
import dbd_lcd.gui.form.FormLogin;
import dbd_lcd.gui.form.barang.DetailBarangFrame.Mode;
import dbd_lcd.system.structs.Barang;
import dbd_lcd.system.structs.filter.FilterBarang;
import dbd_lcd.system.structs.filter.FilterPeminjaman;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author user
 */
public class DetailBarangPanel extends MyPanel {

    /**
     * Creates new form DetailBarangPanel
     */
    public int mode = 0;
    public Barang barang;
    public DetailBarangPanel() {
        initComponents();
    }

    public void setReadOnly(boolean readOnly){
        
        //jenisCB.setEnabled(false);
        //nomorField.setEditable(false);
        
        statusCB.setEnabled(!readOnly && !Barang.Status.DIPINJAM.equals(barang.getStatus()));
        keteranganTA.setEditable(!readOnly);
    }
    
    public void setMode(int mode){
        switch(mode){
            case Mode.LIHAT:{
                setReadOnly(true);
                
                editButton.setVisible(true);
                doneButton.setVisible(true);
                
                getFrame().lockTab(null);
                
                saveButton.setVisible(false);
                cancelEditButton.setVisible(false);
                
                if(barang != null && Barang.Status.DIPINJAM.equals(barang.getStatus())){
                    editButton.setVisible(false);
                }
                break;
            }
            case Mode.EDIT:{
                setReadOnly(false);
                
                saveButton.setVisible(true);
                cancelEditButton.setVisible(true);
                
                getFrame().lockTab(this);
                
                editButton.setVisible(false);
                doneButton.setVisible(false);
                break;
            }
        }
    }
    
    public void load(Barang b){
        this.barang = b;
        setMode(Mode.LIHAT);
        
        nomorField.setText(""+b.getNomor());
        jenisCB.setSelectedItem(b.getTipeString());
        
        if(b.getStatus().equals(Barang.Status.DIPINJAM)){
            statusCB.setModel(new DefaultComboBoxModel(new String[]{
                Barang.Status.TO_STRING.get(Barang.Status.DIPINJAM)
            }));
            statusCB.setSelectedIndex(0);
        }else{
            statusCB.setModel(new DefaultComboBoxModel(
                Barang.Status.STRING_AVAILABLE
            ));
            statusCB.setSelectedItem(b.getStatusString());
        }
        
        statusCB.setBackground(Barang.Status.getColor((String)statusCB.getSelectedItem()).get(false));
        
        keteranganTA.setText(Util.stringify(b.getKeterangan()));
        
    }
    
    public Barang read(){
        Barang b = new Barang(barang);
        //b.setNomor(Integer.parseInt(nomorField.getText()));
        //b.setTipe(Barang.Tipe.FROM_STRING.get(jenisCB.getSelectedItem()));
        b.setStatus(Barang.Status.FROM_STRING.get(statusCB.getSelectedItem()));
        b.setKeterangan(keteranganTA.getText());
        return b;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        LJenis = new javax.swing.JLabel();
        jenisCB = new javax.swing.JComboBox<>();
        LNomor = new javax.swing.JLabel();
        nomorField = new javax.swing.JFormattedTextField();
        LNomor1 = new javax.swing.JLabel();
        statusCB = new javax.swing.JComboBox<>();
        LNomor2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        keteranganTA = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        cancelEditButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        doneButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new java.awt.GridBagLayout());

        LJenis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LJenis.setForeground(new java.awt.Color(255, 255, 255));
        LJenis.setText("Jenis");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 5, 5, 5);
        add(LJenis, gridBagConstraints);

        jenisCB.setModel(new DefaultComboBoxModel<>(Barang.Tipe.STRING));
        jenisCB.setEnabled(false);
        jenisCB.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.75;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jenisCB, gridBagConstraints);

        LNomor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LNomor.setForeground(new java.awt.Color(255, 255, 255));
        LNomor.setText("Nomor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 5, 5, 5);
        add(LNomor, gridBagConstraints);

        nomorField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(nomorField, gridBagConstraints);

        LNomor1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LNomor1.setForeground(new java.awt.Color(255, 255, 255));
        LNomor1.setText("Status");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 5, 5, 5);
        add(LNomor1, gridBagConstraints);

        statusCB.setModel(new DefaultComboBoxModel<>(Barang.Status.STRING_AVAILABLE));
        statusCB.setOpaque(false);
        statusCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusCBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.75;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(statusCB, gridBagConstraints);

        LNomor2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LNomor2.setForeground(new java.awt.Color(255, 255, 255));
        LNomor2.setText("Keterangan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 5, 5, 5);
        add(LNomor2, gridBagConstraints);

        keteranganTA.setColumns(20);
        keteranganTA.setRows(5);
        jScrollPane2.setViewportView(keteranganTA);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jScrollPane2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        cancelEditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbd_lcd/gui/image/SILANG.png"))); // NOI18N
        cancelEditButton.setContentAreaFilled(false);
        cancelEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelEditButtonActionPerformed(evt);
            }
        });
        jPanel3.add(cancelEditButton);

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbd_lcd/gui/image/PENGATURAN.png"))); // NOI18N
        editButton.setContentAreaFilled(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jPanel3.add(editButton);

        doneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbd_lcd/gui/image/CENTANG.png"))); // NOI18N
        doneButton.setContentAreaFilled(false);
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        jPanel3.add(doneButton);

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbd_lcd/gui/image/CENTANG.png"))); // NOI18N
        saveButton.setContentAreaFilled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel3.add(saveButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jPanel3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEditButtonActionPerformed
        // TODO add your handling code here:
        load(barang);
        setMode(Mode.LIHAT);
    }//GEN-LAST:event_cancelEditButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        setMode(Mode.EDIT);
    }//GEN-LAST:event_editButtonActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_doneButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        
        final Barang b;
        try{
            b = read();
        }catch(Exception ex){
            Util.handleException(getFrame(), ex);
            return;
        }
        if(b.equals(barang)){
            setMode(Mode.LIHAT);
            return;
        }
        FormLogin.cekDanMintaSesi(getFrame(), new PopupRunnable(){
            public boolean run(boolean success){
                if(success){
                    barang = b;
                    getFrame().changed = true;
                    b.update();
                    load(b);
                    setMode(Mode.LIHAT);
                }
                return true;
            }
        });
    }//GEN-LAST:event_saveButtonActionPerformed

    private void statusCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusCBActionPerformed
        // TODO add your handling code here:
        statusCB.setBackground(Barang.Status.getColor((String)statusCB.getSelectedItem()).get(false));
    }//GEN-LAST:event_statusCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LJenis;
    private javax.swing.JLabel LNomor;
    private javax.swing.JLabel LNomor1;
    private javax.swing.JLabel LNomor2;
    private javax.swing.JButton cancelEditButton;
    private javax.swing.JButton doneButton;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jenisCB;
    private javax.swing.JTextArea keteranganTA;
    private javax.swing.JFormattedTextField nomorField;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> statusCB;
    // End of variables declaration//GEN-END:variables
}
