/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbd_lcd.gui.form.barang;

import dbd_lcd.Util;
import dbd_lcd.gui.form.peminjaman.DaftarPeminjamanPanel;
import dbd_lcd.system.structs.Barang;
import dbd_lcd.system.structs.filter.FilterBarang;
import dbd_lcd.system.structs.filter.FilterPeminjaman;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author user
 */
public class DetailBarangFrame extends dbd_lcd.gui.MyFrame {

    public static class Mode{
        public static final int LIHAT = 0;
        public static final int EDIT = 1;
    }
    
    Barang barang;
    /**
     * Creates new form DetailBarang
     */
    public int mode = 0;
    
    public DetailBarangFrame() {
        initComponents();
        setMode(Mode.LIHAT);
    }
    
    public void setMode(int mode){
        switch(mode){
            
        }
        detailBarangPanel.setMode(mode);
    }
    
    public void load(Barang b){
        this.barang = b;
        
        detailBarangPanel.load(b);
        setMode(Mode.LIHAT);
        
        
        FilterPeminjaman fp = daftarPeminjamanPanel.getFilter();
        FilterBarang filter = fp.barang;
        if(filter == null){
            filter = new FilterBarang();
        }
        filter.tipe = barang.getTipe();
        filter.nomor = barang.getNomor();
        fp.barang = filter;
        daftarPeminjamanPanel.setFilter(fp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        LJudul = new javax.swing.JLabel();
        mainTabbedPane = new javax.swing.JTabbedPane();
        detailBarangPanel = new dbd_lcd.gui.form.barang.DetailBarangPanel();
        daftarPeminjamanPanel = new dbd_lcd.gui.form.peminjaman.DaftarPeminjamanPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        LJudul.setBackground(new java.awt.Color(255, 153, 0));
        LJudul.setFont(new java.awt.Font("Comic Sans MS", 1, 26)); // NOI18N
        LJudul.setForeground(new java.awt.Color(255, 255, 255));
        LJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LJudul.setText("Detail Barang");
        LJudul.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(LJudul, gridBagConstraints);

        mainTabbedPane.setBackground(new java.awt.Color(0, 102, 102));
        mainTabbedPane.setOpaque(true);
        mainTabbedPane.addTab("Detail", detailBarangPanel);
        mainTabbedPane.addTab("Peminjaman", daftarPeminjamanPanel);
        daftarPeminjamanPanel.setMode(DaftarPeminjamanPanel.Mode.SUB);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(mainTabbedPane, gridBagConstraints);
        setTabbedPane(mainTabbedPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailBarangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailBarangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailBarangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailBarangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailBarangFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LJudul;
    private dbd_lcd.gui.form.peminjaman.DaftarPeminjamanPanel daftarPeminjamanPanel;
    private dbd_lcd.gui.form.barang.DetailBarangPanel detailBarangPanel;
    private javax.swing.JTabbedPane mainTabbedPane;
    // End of variables declaration//GEN-END:variables
}
